language: go
go:
- tip
before_install:
- go get github.com/mattn/gom
script:
- $HOME/gopath/bin/gom install
- $HOME/gopath/bin/gom build -o bin/arkenctl
- $HOME/gopath/bin/gom test
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIB2SVB7S6ZENR7DA
  secret_access_key:
    secure: LFaBtlKL6bs+cKxUWIrIC2Z9KhVyCBz6/2LFnD/wIaayDv4pcCIFJ9j4wsAPF8jGuaOrAzdZJ1ZjZtTRGNIpumwln2c6rf4jJ9xQ7NdKIgdtod6DCUYds5JqALYOb+lQhkbmQNCX7M82Pzg4dqXlxcdguwr+GwYED+p/OnACbRg=
  bucket: gogeta
  local-dir: bin
