language: go
go:
- tip
before_install:
- go get github.com/mattn/gom
script:
- $HOME/gopath/bin/gom install
- $HOME/gopath/bin/gom build -o bin/arkenctl
- $HOME/gopath/bin/gom test
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIUJMCCUP5PWE2AOA
  secret_access_key:
    secure: ID5FLsupzrzIFUfAsi5VicQOa9zsoO5pxe88SEenRFoE/xgQm3++bAkTIXOjUTxse67GiQLI3htY+q5cXoS/p/pN1hnwq0gzRWlAiRhUI+TnvqieOIp1usBc37usbfss+zvGFZYcL1DbafALp7WrddtVLUxbkJHJ+Fm12D4+YZ4=
  bucket: gogeta
  local-dir: bin
