language: go
go:
- tip
before_install:
- go get github.com/mattn/gom
script:
- $HOME/gopath/bin/gom install
- $HOME/gopath/bin/gom build -o bin/arkenctl
- $HOME/gopath/bin/gom test
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIB2SVB7S6ZENR7DA
  secret_access_key:
    secure: OcS0ihiqJmtZxKRwi9DS5QSBBvsYgUfc9ParDte3P078gA/McLgUs6GsfSDOrPAcQ1v/V+/Kas69elVi2sjhSSGbY08nvnZsYk1iz3xDJFqv1BSFoIyGsEbD4PmIyKiDyxKT5IepYmMY+khnpmeT7WK3Ddzmr15NP4vyDc+EZQ0=
  bucket: gogeta
  local-dir: bin

